### ISSUE TITLE
Solicitação para ser membro da comunidade

### ISSUE THREAD

**Issue by inolopesm** [Comunidade-para-Software-Livre-Aberto/Comunidade-para-Software-Livre-Aberto#2]
Por favor, me adicionar como membro da comunidade

**Comment by luisvonmuller** [comment]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/35612741/143614513-b64dffa6-ab94-4a24-8dc8-34e78a2101ad.png">
Here u go. Close.
